In [24]:
import pandas as pd
import numpy as np

In [25]:
# 1. Carregar o dataset
srp = pd.read_csv("./DATASET/survey_results_public.csv")

# 2. Lista de valores inválidos
valores_invalidos = ['?', 'n.a', 'n.a.', 'NA', 'na', 'N/A']

# 3. Substituir esses valores por NaN
srp = srp.replace(valores_invalidos, np.nan)

# 4. Criar 3 cópias do dataset original
dataset_media = srp.copy()
dataset_mediana = srp.copy()
dataset_zero = srp.copy()

# 5. Selecionar apenas colunas numéricas
colunas_numericas = srp.select_dtypes(include=[np.number]).columns

# 6. Preencher valores em falta nas colunas numéricas
for col in colunas_numericas:
    dataset_media[col] = dataset_media[col].fillna(dataset_media[col].mean())
    dataset_mediana[col] = dataset_mediana[col].fillna(dataset_mediana[col].median())
    dataset_zero[col] = dataset_zero[col].fillna(0)

# 7. Se quiseres também tratar colunas de texto, podes preencher com "Sem dado"
colunas_texto = srp.select_dtypes(include=["object"]).columns

for col in colunas_texto:
    dataset_media[col] = dataset_media[col].fillna("Sem dado")
    dataset_mediana[col] = dataset_mediana[col].fillna("Sem dado")
    dataset_zero[col] = dataset_zero[col].fillna("Sem dado")

# 8. Guardar os 3 novos datasets em ficheiros CSV
dataset_media.to_csv("./DATASET/dataset_limpo_media.csv", index=False)
dataset_mediana.to_csv("./DATASET/dataset_limpo_mediana.csv", index=False)
dataset_zero.to_csv("./DATASET/dataset_limpo_zero.csv", index=False)

print("Os 3 ficheiros foram criados com sucesso na pasta DATASET.")

Os 3 ficheiros foram criados com sucesso na pasta DATASET.

In [26]:
dataset_media.isna().sum()

ResponseId             0
MainBranch             0
Age                    0
Employment             0
RemoteWork             0
                      ..
JobSatPoints_11        0
SurveyLength           0
SurveyEase             0
ConvertedCompYearly    0
JobSat                 0
Length: 114, dtype: int64

In [27]:
dataset_mediana.isna().sum()

ResponseId             0
MainBranch             0
Age                    0
Employment             0
RemoteWork             0
                      ..
JobSatPoints_11        0
SurveyLength           0
SurveyEase             0
ConvertedCompYearly    0
JobSat                 0
Length: 114, dtype: int64

In [28]:
dataset_zero.isna().sum()

ResponseId             0
MainBranch             0
Age                    0
Employment             0
RemoteWork             0
                      ..
JobSatPoints_11        0
SurveyLength           0
SurveyEase             0
ConvertedCompYearly    0
JobSat                 0
Length: 114, dtype: int64

In [29]:
dataset_media.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65437 entries, 0 to 65436
Columns: 114 entries, ResponseId to JobSat
dtypes: float64(13), int64(1), object(100)
memory usage: 56.9+ MB

In [30]:
dataset_mediana.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65437 entries, 0 to 65436
Columns: 114 entries, ResponseId to JobSat
dtypes: float64(13), int64(1), object(100)
memory usage: 56.9+ MB

In [31]:
dataset_media.compare(dataset_mediana)

           CompTotal              WorkExp       JobSatPoints_1        \
                self     other       self other           self other
0      2.963841e+145  110000.0  11.466957   9.0      18.581094  10.0
1      2.963841e+145  110000.0        NaN   NaN            NaN   NaN
2      2.963841e+145  110000.0  11.466957   9.0      18.581094  10.0
3      2.963841e+145  110000.0  11.466957   9.0      18.581094  10.0
4      2.963841e+145  110000.0  11.466957   9.0      18.581094  10.0
...              ...       ...        ...   ...            ...   ...
65432  2.963841e+145  110000.0  11.466957   9.0      18.581094  10.0
65433  2.963841e+145  110000.0  11.466957   9.0      18.581094  10.0
65434  2.963841e+145  110000.0  11.466957   9.0      18.581094  10.0
65435  2.963841e+145  110000.0        NaN   NaN            NaN   NaN
65436  2.963841e+145  110000.0  11.466957   9.0      18.581094  10.0

      JobSatPoints_4       JobSatPoints_5        ... JobSatPoints_9        \
                self other           self other  ...           self other
0            7.52214   0.0      10.060857   0.0  ...      16.169432   5.0
1                NaN   NaN            NaN   NaN  ...            NaN   NaN
2            7.52214   0.0      10.060857   0.0  ...      16.169432   5.0
3            7.52214   0.0      10.060857   0.0  ...      16.169432   5.0
4            7.52214   0.0      10.060857   0.0  ...      16.169432   5.0
...              ...   ...            ...   ...  ...            ...   ...
65432        7.52214   0.0      10.060857   0.0  ...      16.169432   5.0
65433        7.52214   0.0      10.060857   0.0  ...      16.169432   5.0
65434        7.52214   0.0      10.060857   0.0  ...      16.169432   5.0
65435            NaN   NaN            NaN   NaN  ...            NaN   NaN
65436        7.52214   0.0      10.060857   0.0  ...      16.169432   5.0

      JobSatPoints_10       JobSatPoints_11       ConvertedCompYearly  \
                 self other            self other                self
0           10.955713   0.0        9.953948   0.0        86155.287263
1                 NaN   NaN             NaN   NaN        86155.287263
2           10.955713   0.0        9.953948   0.0        86155.287263
3           10.955713   0.0        9.953948   0.0        86155.287263
4           10.955713   0.0        9.953948   0.0        86155.287263
...               ...   ...             ...   ...                 ...
65432       10.955713   0.0        9.953948   0.0        86155.287263
65433       10.955713   0.0        9.953948   0.0        86155.287263
65434       10.955713   0.0        9.953948   0.0        86155.287263
65435             NaN   NaN             NaN   NaN        86155.287263
65436       10.955713   0.0        9.953948   0.0        86155.287263

                  JobSat
         other      self other
0      65000.0  6.935041   7.0
1      65000.0  6.935041   7.0
2      65000.0  6.935041   7.0
3      65000.0  6.935041   7.0
4      65000.0  6.935041   7.0
...        ...       ...   ...
65432  65000.0  6.935041   7.0
65433  65000.0  6.935041   7.0
65434  65000.0  6.935041   7.0
65435  65000.0  6.935041   7.0
65436  65000.0  6.935041   7.0

[49642 rows x 26 columns]

In [32]:
dataset_media.isna().sum().sum()

np.int64(0)

In [33]:
dataset_mediana.isna().sum().sum()

np.int64(0)

In [34]:
dataset_media.isna().sum().sort_values(ascending=False)

ResponseId             0
MainBranch             0
Age                    0
Employment             0
RemoteWork             0
                      ..
JobSatPoints_11        0
SurveyLength           0
SurveyEase             0
ConvertedCompYearly    0
JobSat                 0
Length: 114, dtype: int64

In [35]:
# 1. Carregar o dataset limpo (com zero)
srp = pd.read_csv('DATASET/dataset_limpo_mediana.csv')
#LIMPEZA: Transformar o texto em intervalos simples
# Removemos "years old", "Under", etc.
srp['Age'] = (srp['Age']
             .str.replace(' years old', '', regex=False)
             .str.replace('Under ', '<', regex=False)
             .str.replace(' years or older', '+', regex=False))

In [36]:
# CRIAR A VARIÁVEL NUMÉRICA DE GAMAS (Age_Code)
# A professora sugeriu isto para que a variável seja tratada como um "valor"
# Atribuímos um peso de 1 a 7 para cada faixa etária
map_num = {
    '<18': 1, 
    '18-24': 2, 
    '25-34': 3, 
    '35-44': 4, 
    '45-54': 5, 
    '55-64': 6, 
    '65+': 7,
    'Prefer not to say': 0  # Atribuímos 0 para quem não quis dizer
}
srp['Age_Code'] = srp['Age'].map(map_num)
srp['Age_Code'] = srp['Age_Code'].astype(int)

In [37]:
# CRIAÇÃO DA VARIÁVEL DE GERAÇÕES (Variável qualitativa)
map_gen = {
    '<18': 'Gen Alpha', 
    '18-24': 'Gen Z', 
    '25-34': 'Millennials', 
    '35-44': 'Millennials/Gen X', 
    '45-54': 'Gen X', 
    '55-64': 'Boomers', 
    '65+': 'Silent Generation',
    'Prefer not to say': 'Não Declarado'
}
srp['Geração'] = srp['Age'].map(map_gen)

In [38]:
# VERIFICAÇÃO
print("Novas variáveis criadas com sucesso:")
print(srp[['Age', 'Age_Code', 'Geração']].head(10))

Novas variáveis criadas com sucesso:
     Age  Age_Code            Geração
0    <18         1          Gen Alpha
1  35-44         4  Millennials/Gen X
2  45-54         5              Gen X
3  18-24         2              Gen Z
4  18-24         2              Gen Z
5    <18         1          Gen Alpha
6  35-44         4  Millennials/Gen X
7  18-24         2              Gen Z
8  45-54         5              Gen X
9  35-44         4  Millennials/Gen X

In [39]:
# Mostrar a contagem de nulos em todas as colunas (foi apenas uma validação para garantir que não há mais nulos)
print(srp.isnull().sum())

ResponseId             0
MainBranch             0
Age                    0
Employment             0
RemoteWork             0
                      ..
SurveyEase             0
ConvertedCompYearly    0
JobSat                 0
Age_Code               0
Geração                0
Length: 116, dtype: int64

In [40]:
#SALVAR NUMA NOVA CÓPIA (Juntei o meu trabalho com o dataset limpo zero do Luís)
srp.to_csv('DATASET/dataset_limpo_medianag.csv', index=False)

In [58]:
#1º chamamos o nosso dataset limpo e com as novas colunas das gerações
#2º  escolhemos as variáveis (colunas) que vamos usar na nossa análise estatística - apenas colunas numéricas
#3º Verificamos qual o nome das nossas colunas 
#4º Vemos também qual a dimensão do nosso novo dataset numérico

data = dataset_medianag.select_dtypes(include="number")


print("Colunas numéricas:")
print(data.columns)

print("\nDimensão do dataset numérico:")
print(data.shape)

Colunas numéricas:
Index(['ResponseId', 'CompTotal', 'WorkExp', 'JobSatPoints_1',
       'JobSatPoints_4', 'JobSatPoints_5', 'JobSatPoints_6', 'JobSatPoints_7',
       'JobSatPoints_8', 'JobSatPoints_9', 'JobSatPoints_10',
       'JobSatPoints_11', 'ConvertedCompYearly', 'JobSat', 'Age_Code'],
      dtype='object')

Dimensão do dataset numérico:
(65437, 15)

In [59]:
#Vamos usar o describe para verificar as principais estatisticas - média, max. min...

print("ESTATÍSTICAS DESCRITIVAS GERAIS")
display(data.describe())

ESTATÍSTICAS DESCRITIVAS GERAIS

,ResponseId,CompTotal,WorkExp,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,ConvertedCompYearly,JobSat,Age_Code
count,65437.000000,6.543700e+04,65437.000000,65437.000000,65437.000000,65437.000000,65437.000000,65437.000000,65437.000000,65437.000000,65437.000000,65437.000000,6.543700e+04,65437.000000,65437.000000
mean,32719.000000,1.528187e+145,10.118098,13.845409,3.378796,4.521905,21.954677,18.584513,14.626643,10.027841,4.930632,4.479026,7.257636e+04,6.971087,3.275884
std,18890.179119,3.909204e+147,6.293516,17.898368,12.901399,15.469507,18.300966,18.552441,18.247594,17.570898,16.304722,15.423596,1.122207e+05,1.393560,1.222237
min,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000e+00,0.000000,0.000000
25%,16360.000000,1.030000e+05,9.000000,10.000000,0.000000,0.000000,20.000000,15.000000,10.000000,5.000000,0.000000,0.000000,6.500000e+04,7.000000,2.000000
50%,32719.000000,1.100000e+05,9.000000,10.000000,0.000000,0.000000,20.000000,15.000000,10.000000,5.000000,0.000000,0.000000,6.500000e+04,7.000000,3.000000
75%,49078.000000,1.140000e+05,9.000000,10.000000,0.000000,0.000000,20.000000,15.000000,10.000000,5.000000,0.000000,0.000000,6.500000e+04,7.000000,4.000000
max,65437.000000,1.000000e+150,50.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,1.625660e+07,10.000000,7.000000

In [66]:
#Criamos uma tabela com as pricipais estatisticas que não estão presentes no describe()

estatisticas = pd.DataFrame({
    "Mediana": data.median(),
    "Variância": data.var(),
    "Desvio Padrão": data.std()
})

estatisticas

                      Mediana      Variância  Desvio Padrão
ResponseId            32719.0   3.568389e+08   1.889018e+04
CompTotal            110000.0  1.528187e+295  3.909204e+147
WorkExp                   9.0   3.960834e+01   6.293516e+00
JobSatPoints_1           10.0   3.203516e+02   1.789837e+01
JobSatPoints_4            0.0   1.664461e+02   1.290140e+01
JobSatPoints_5            0.0   2.393056e+02   1.546951e+01
JobSatPoints_6           20.0   3.349254e+02   1.830097e+01
JobSatPoints_7           15.0   3.441931e+02   1.855244e+01
JobSatPoints_8           10.0   3.329747e+02   1.824759e+01
JobSatPoints_9            5.0   3.087365e+02   1.757090e+01
JobSatPoints_10           0.0   2.658440e+02   1.630472e+01
JobSatPoints_11           0.0   2.378873e+02   1.542360e+01
ConvertedCompYearly   65000.0   1.259348e+10   1.122207e+05
JobSat                    7.0   1.942009e+00   1.393560e+00
Age_Code                  3.0   1.493864e+00   1.222237e+00

In [65]:
#De seguida fazemos os cáclculo dos quartis e cálculamos também o IQR (mostra onde está concetrada a maioria dos dados)

quartis = pd.DataFrame({
    "Q1 (25%)": data.quantile(0.25),
    "Q2 (50% / Mediana)": data.quantile(0.50),
    "Q3 (75%)": data.quantile(0.75),
    "IQR": data.quantile(0.75) - data.quantile(0.25)
})

quartis

                     Q1 (25%)  Q2 (50% / Mediana)  Q3 (75%)      IQR
ResponseId            16360.0             32719.0   49078.0  32718.0
CompTotal            103000.0            110000.0  114000.0  11000.0
WorkExp                   9.0                 9.0       9.0      0.0
JobSatPoints_1           10.0                10.0      10.0      0.0
JobSatPoints_4            0.0                 0.0       0.0      0.0
JobSatPoints_5            0.0                 0.0       0.0      0.0
JobSatPoints_6           20.0                20.0      20.0      0.0
JobSatPoints_7           15.0                15.0      15.0      0.0
JobSatPoints_8           10.0                10.0      10.0      0.0
JobSatPoints_9            5.0                 5.0       5.0      0.0
JobSatPoints_10           0.0                 0.0       0.0      0.0
JobSatPoints_11           0.0                 0.0       0.0      0.0
ConvertedCompYearly   65000.0             65000.0   65000.0      0.0
JobSat                    7.0                 7.0       7.0      0.0
Age_Code                  2.0                 3.0       4.0      2.0

In [ ]:
#Através da covariancia, conseguimos visualizar como as duas variaveis variam em conjunto.
#NEste caso, vemos um valor positivo o que seignifica que tendem a aumentar juntas, logo
#Quanto mais experiencia, melhor é o salário

covariancia = data[["WorkExp", "ConvertedCompYearly"]].cov()
covariancia

                          WorkExp  ConvertedCompYearly
WorkExp                 39.608340         6.048068e+04
ConvertedCompYearly  60480.678865         1.259348e+10

In [ ]:
#Com a correlação conseguimos verificar o grau de relação entre duas variáveis.
#Neste caso a correlação é bastante baixa, cerca de 0.086, ou seja, quase não existe correlação entre a Experienci de trabalho e o salário anual convertido

corr = data[["WorkExp", "ConvertedCompYearly"]].corr()
corr

                      WorkExp  ConvertedCompYearly
WorkExp              1.000000             0.085635
ConvertedCompYearly  0.085635             1.000000

In [85]:
#Neste caso já é diferente, aqui já conseguimos identificar uma correlação de 0.48, o que significa que é Moderada.
#Ou seja, a Experiencia tem alguma coisa a ver com os Anos de Código
corrB = data[['WorkExp', 'Age_Code']].corr()
corrB

           WorkExp  Age_Code
WorkExp   1.000000  0.475688
Age_Code  0.475688  1.000000

In [ ]:
#Converter a variavel para numérico, todos os registos que contivesse:
#Sem dado - passa a ser 0 (ou seja, nada)
#Se disser - Less than 1 year, passa a 0.5 e
#Se disser - more than 50 year, passa a 50

dataset_medianag["YearsCode"] = dataset_medianag["YearsCode"].replace({
    "Sem dado": 0,
    "Less than 1 year": 0.5,
    "More than 50 years": 50
})

dataset_medianag["YearsCode"] = pd.to_numeric(dataset_medianag["YearsCode"])

In [ ]:
#Fazemos o mesmo que o anterior, mas para a variável YearsCodePro

dataset_medianag["YearsCodePro"] = dataset_medianag["YearsCodePro"].replace({
    "Sem dado": 0,
    "Less than 1 year": 0.5,
    "More than 50 years": 50
})

dataset_medianag["YearsCodePro"] = pd.to_numeric(dataset_medianag["YearsCodePro"])

In [91]:
#Verificamos novamente quais as colunas que estão como numérico

data = dataset_medianag.select_dtypes(include="number")
data.columns

Index(['ResponseId', 'YearsCode', 'YearsCodePro', 'CompTotal', 'WorkExp',
       'JobSatPoints_1', 'JobSatPoints_4', 'JobSatPoints_5', 'JobSatPoints_6',
       'JobSatPoints_7', 'JobSatPoints_8', 'JobSatPoints_9', 'JobSatPoints_10',
       'JobSatPoints_11', 'ConvertedCompYearly', 'JobSat', 'Age_Code'],
      dtype='object')

In [92]:
#Correlações Especificas

In [ ]:
#Experiência Profissional vs Anos de Código

corr_A = data[["WorkExp", "YearsCode"]].corr()
corr_A

#Verificamos então que existe uma correlação moderada entre estas duas variáveis.

            WorkExp  YearsCode
WorkExp    1.000000   0.546866
YearsCode  0.546866   1.000000

In [95]:
#Experiência profissional vs Anos de Código Profissional
corr_B = data[["WorkExp", "YearsCodePro"]].corr()
corr_B

##Verificamos então que existe uma correlação moderada entre estas duas variáveis. E é uma correlação um pouco mais forte que a anterior

               WorkExp  YearsCodePro
WorkExp       1.000000      0.585508
YearsCodePro  0.585508      1.000000

In [98]:
#Satisfação no trabalho vs Salário Anual
corr_C = data[["JobSat", "ConvertedCompYearly"]].corr()
corr_C

#Correlação muito baixa, quase inexistente

                       JobSat  ConvertedCompYearly
JobSat               1.000000             0.026164
ConvertedCompYearly  0.026164             1.000000

In [100]:
#Satisfação no trabalho vs experiência
corr_D = data[["JobSat", "WorkExp"]].corr()
corr_D

##Correlação muito baixa, quase inexistente

           JobSat   WorkExp
JobSat   1.000000  0.090001
WorkExp  0.090001  1.000000

In [105]:
percentis = pd.DataFrame({
    "WorkExp": data["WorkExp"].quantile([0.10, 0.25, 0.50, 0.75, 0.90]),
    "ConvertedCompYearly": data["ConvertedCompYearly"].quantile([0.10, 0.25, 0.50, 0.75, 0.90]),
    "YearsCode": data["YearsCode"].quantile([0.10, 0.25, 0.50, 0.75, 0.90]),
    "YearsCodePro": data["YearsCodePro"].quantile([0.10, 0.25, 0.50, 0.75, 0.90])
})
percentis

#Anos de Experiencia:
    #10% dos developers têm até 4 anos de experiência
    #50% (mediana) têm cerca de 9 anos
    #90% têm até 17 anos, ou seja, A maioria dos developers do dataset tem entre 4 e 17 anos de experiência.

#Salário Anual
    #10% ganham até 37592 USD
    #50% (mediana) ganham 65000 USD
    #90% ganham até 101910 USD, ou seja, o salário típico dos developers está perto de 65000 USD.

#Anos a Programar
    #10% têm 1 ano de experiência em programação
    #50% têm cerca de 10 anos
    #90% têm até 30 anos, ou seja, muitos developers começam a programar antes da carreira profissional.

#Anos a programar profissionalmente
    #10% têm 0 anos
    #50% têm 5 anos
    #90% têm 21 anos, ou seja, conseguimos ver que existe una grande diferença entre os Anos de código e os anos de codio profissional

      WorkExp  ConvertedCompYearly  YearsCode  YearsCodePro
0.10      4.0              37592.0        1.0           0.0
0.25      9.0              65000.0        5.0           0.5
0.50      9.0              65000.0       10.0           5.0
0.75      9.0              65000.0       18.0          12.0
0.90     17.0             101910.0       30.0          21.0

In [108]:
Q1 = data.quantile(0.25)
Q3 = data.quantile(0.75)
IQR = Q3 - Q1

outliers = ((data < (Q1 - 1.5 * IQR)) | (data > (Q3 + 1.5 * IQR))).sum()

outliers_data = pd.DataFrame({
    "Número de Outliers": outliers,
    "Percentagem de Outliers (%)": (outliers / len(data)) * 100
})

outliers_data.sort_values(by="Número de Outliers", ascending=False)

                     Número de Outliers  Percentagem de Outliers (%)
WorkExp                           28676                    43.822302
CompTotal                         28132                    42.990968
JobSatPoints_7                    27847                    42.555435
JobSatPoints_9                    27569                    42.130599
JobSatPoints_8                    25844                    39.494476
JobSatPoints_1                    25314                    38.684536
JobSatPoints_6                    25098                    38.354448
ConvertedCompYearly               23398                    35.756529
JobSat                            22747                    34.761679
JobSatPoints_10                   12121                    18.523160
JobSatPoints_5                    11594                    17.717805
JobSatPoints_11                   11155                    17.046931
JobSatPoints_4                     9477                    14.482632
YearsCode                          3074                     4.697648
YearsCodePro                       2541                     3.883124
ResponseId                            0                     0.000000
Age_Code                              0                     0.000000

In [109]:
#EM primeiro lugar cálculamos os quartis (Q1 e Q2), para depois conseguirmos calcular o IQR (para ver onde os dados estavam concetrados).
#O vaçor é considerado um outlier se estiver abaixo de Q1 - 1.5 * IQR ou acima de Q3 + 1.5 * IQR
#Com os resultados conseguimos ver que as variaveis que estão relacionadas a experiencia ou salário tem um maior número de outliers, 
#isso pode ser explciado porque existe uma grande variedade no mercado de trabalho, de diferentes países, niveis de experiencia...

In [ ]:
print("TOP 10 MAIORES SALÁRIOS")
display(data[["WorkExp", "YearsCode", "YearsCodePro", "ConvertedCompYearly", "Age_Code", "JobSat"]]
        .sort_values(by="ConvertedCompYearly", ascending=False)
        .head(10))

#Aqui conseguimos visualizer quais os 10 funcionários que possuem o maior salário.
#Vemos também que os anos de experiencia não signifca que se tenha um salário maior, por exemplo:
        #o 12723 tem 4 anos de experiencia e ganha 13 818 022 enquanto que o 13763 tem 12 anos de experiencia e ganha apenas 2 048 046

TOP 10 MAIORES SALÁRIOS

       WorkExp  YearsCode  YearsCodePro  ConvertedCompYearly  Age_Code  JobSat
15837      9.0       16.0           5.0           16256603.0         3     7.0
12723      4.0        5.0          10.0           13818022.0         3    10.0
28379     15.0       15.0           7.0            9000000.0         2    10.0
17593     13.0       16.0          13.0            6340564.0         4     6.0
17672     11.0       16.0          11.0            4936778.0         3     7.0
19267      7.0       13.0           7.0            3367716.0         3     7.0
23694      9.0        9.0           5.0            2584118.0         2     7.0
33720      9.0        9.0           5.0            2237846.0         3     7.0
34523      2.0        6.0           2.0            2153432.0         2    10.0
13763     12.0       15.0          12.0            2048046.0         4    10.0

In [119]:
print("TOP 10 MENORES SALÁRIOS")

display(
    data[data["ConvertedCompYearly"] > 5000][["WorkExp", "YearsCode", "YearsCodePro", "ConvertedCompYearly", "Age_Code", "JobSat"]]
    .sort_values(by="ConvertedCompYearly", ascending=True)
    .head(10)
)

#Aqui é a mesma coisa que em cima, mas os 10 funcionários que ganahm menos

TOP 10 MENORES SALÁRIOS

       WorkExp  YearsCode  YearsCodePro  ConvertedCompYearly  Age_Code  JobSat
12171      1.0        2.0           1.0               5025.0         3     5.0
18816      2.0        7.0           2.0               5025.0         3     6.0
5021       1.0        4.0           1.0               5025.0         2     7.0
11252      0.0        6.0           0.5               5025.0         3     6.0
35971      2.0        5.0           1.0               5025.0         3     6.0
20682      4.0       13.0           3.0               5025.0         3     7.0
39229      2.0        7.0           2.0               5025.0         3     5.0
2967       2.0        4.0           2.0               5025.0         2     3.0
12045      2.0        4.0           1.0               5025.0         2     7.0
28553      9.0        5.0           9.0               5051.0         3     7.0